#define _CRT_SECURE_NO_WARNINGS
#include <stdint.h>
#include <stdlib.h>
#include <memory.h>
#include <string.h>
#include <stdio.h>
#include <math.h>
#include <Winsock2.h>
#include <Windows.h>
#include <dbghelp.h>
#include <processthreadsapi.h>
#include <GL/gl.h>
#define SDL_MAIN_HANDLED
#include "SDL.h"
#define STBI_ONLY_PNG
#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"
